### ISSUE TITLE
229 warnings

### ISSUE THREAD

**Issue by u84six** [PopMedNet-Team/Mobile-Application#12]
I've cloned the latest version and I'm running xcode 10.1. When I attempt to build the project, I'm getting 229 warnings and 1 build error "Uncategorized - Command PhaseScriptExecution failed with a nonzero exit code".

A lot of the warnings are "Validate Project Settings", and many are "Swift 3 mode has been deprecated....". Some are Swift conversions, and then there are many that are specific, like: "Format String Issue - NSInteger should not be used as format arguments; add an explicit cast to "long" instead".

Should I be using a different version of xcode or possibly make changes to project settings for this app to build?

**Comment by u84six** [comment]
Ok, I'm fairly new to iOS dev. I see that this is using Swift 3. Is there a plan to migrate to the latest version?

**Comment by FDA-MyStudies** [comment]
Hi @u84six ,
Thank you for your interest in the MyStudies system. Apologies for the almost year-long delay in responding. We only recently acquired additional funding to support open-source activities.   In response to your original question, it seems to be an issue with the build time scripts.  We would need some more logs to look into that.  However, we'd suggest you check out the latest code which supports Xcode 11 and Swift 5.0, and that should work fine.

**Comment by doomlab** [comment]
@FDA-MyStudies - unfortunately, you are incorrect. It still does not build:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/27783894/72536112-a2992380-3847-11ea-8a90-fe2086189037.png">

Neither does the Android - even after we fixed a different java error:
 
![image](https://user-images.githubusercontent.com/27783894/72536201-d07e6800-3847-11ea-9bea-f43aefdd4d9a.png)

Does one of the previous branches work? Or any suggestions on how to get these to even build to work with it?

**Comment by seifscape** [comment]
> @FDA-MyStudies - unfortunately, you are incorrect. It still does not build:
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/27783894/72536112-a2992380-3847-11ea-8a90-fe2086189037.png">
> 
> Neither does the Android - even after we fixed a different java error:
> 
> ![image](https://user-images.githubusercontent.com/27783894/72536201-d07e6800-3847-11ea-9bea-f43aefdd4d9a.png)
> 
> Does one of the previous branches work? Or any suggestions on how to get these to even build to work with it?

@doomlab for the iOS you need to update the Podfile to:

Last login: Fri Jan 24 18:14:20 on ttys000
You have new mail.
When the candles are out all women are fair.
		-- Plutarch
-bash: THIS: command not found

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
seifkobrosly@Sarie3:~ $ cd Users/seifkobrosly/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC/
-bash: cd: Users/seifkobrosly/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC/: No such file or directory
seifkobrosly@Sarie3:~ $ cd /Users/seifkobrosly/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC/
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC $ ls
ActivityBuilder            Controllers                GatewayModule              NotificationModule         StudyModel
ActivityModel              DashboardModel             Info.plist                 OtherAssets                SyncUpdate
ActivityResultModel        Database                   Info.plist.orig            OverviewModule             UIReference screens
ActivityStepModel          DownloadManager            Info_BACKUP_7025.plist     Performance.swift          UserModel
ActivityStepResultModel    Eligibility                Info_BASE_7025.plist       ProgressView.xib           Utilities
AppDelegate.swift          EncoderModel               Info_LOCAL_7025.plist      RepeatableFormStep         ViewController.swift
AppGlossary.pdf            External Libraries         Info_REMOTE_7025.plist     ResearchkitContainer       ViewController.swift.orig
Assets.xcassets            FDA.entitlements           JailbrokeBlocker           ResourceModel              WebViewController.swift
Base.lproj                 FetalKickCounterModel      JsonFiles                  ScheduleModel
Branding                   FileModel                  Logger                     Settings
Consent                    Fonts                      NetworkModule              SplashViewController.swift
Constants                  ForceUpdate                NewProgressView.xib        StepProvider
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC $ clear
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC $ ls
ActivityBuilder            Controllers                GatewayModule              NotificationModule         StudyModel
ActivityModel              DashboardModel             Info.plist                 OtherAssets                SyncUpdate
ActivityResultModel        Database                   Info.plist.orig            OverviewModule             UIReference screens
ActivityStepModel          DownloadManager            Info_BACKUP_7025.plist     Performance.swift          UserModel
ActivityStepResultModel    Eligibility                Info_BASE_7025.plist       ProgressView.xib           Utilities
AppDelegate.swift          EncoderModel               Info_LOCAL_7025.plist      RepeatableFormStep         ViewController.swift
AppGlossary.pdf            External Libraries         Info_REMOTE_7025.plist     ResearchkitContainer       ViewController.swift.orig
Assets.xcassets            FDA.entitlements           JailbrokeBlocker           ResourceModel              WebViewController.swift
Base.lproj                 FetalKickCounterModel      JsonFiles                  ScheduleModel
Branding                   FileModel                  Logger                     Settings
Consent                    Fonts                      NetworkModule              SplashViewController.swift
Constants                  ForceUpdate                NewProgressView.xib        StepProvider
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC/HPHC $ cd ..
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ ls
HPHC                  HPHC.xcworkspace      HPHCUITests           Podfile.lock          ResearchKit
HPHC.xcodeproj        HPHCTests             Podfile               Pods                  ResearchKit.xcodeproj
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ rvm use default
Warning! PATH is not properly set up, '/Users/seifkobrosly/.rvm/gems/ruby-2.2.8/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.2.8'.
project 'HPHC.xcodeproj/'
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
project 'HPHC.xcodeproj/'
Using /Users/seifkobrosly/.rvm/gems/ruby-2.2.8
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 13 total pods installed.

[!] Automatically assigning platform `iOS` with version `11.0` on target `HPHC` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `12.2` on target `HPHCUITests` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `12.1` on target `HPHCTests` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] The `HPHC [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-HPHC/Pods-HPHC.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `HPHC [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-HPHC/Pods-HPHC.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 13 total pods installed.

[!] Automatically assigning platform `iOS` with version `11.0` on target `HPHC` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `12.2` on target `HPHCUITests` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

[!] Automatically assigning platform `iOS` with version `12.1` on target `HPHCTests` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ vi Podfile
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ vi Podfile
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ clear
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 13 total pods installed.
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ rm -rf Pods/ Podfile.lock
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ pod install
Analyzing dependencies
Pre-downloading: `SlideMenuControllerSwift` from `https://github.com/AtomicSLLC/SlideMenuControllerSwift.git`, branch `swift5`
Downloading dependencies
Installing ActionSheetPicker-3.0 (2.4.1)
Installing Crashlytics (3.14.0)
Installing CryptoSwift (1.3.0)
Installing Embassy (4.1.1)
Installing EnvoyAmbassador (4.0.5)
Installing Fabric (1.10.2)
Installing IQKeyboardManagerSwift (6.5.4)
Installing Mockingjay (3.0.0-alpha.1)
Installing Realm (4.3.0)
Installing RealmSwift (4.3.0)
Installing SDWebImage (5.4.2)
Installing SlideMenuControllerSwift (5.0.0)
Installing URITemplate (3.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 13 total pods installed.
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ pod install
Analyzing dependencies
Downloading dependencies
Installing Realm 3.20.0 (was 4.3.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Installing RealmSwift 3.20.0 (was 4.3.0 and source changed to `https://cdn.cocoapods.org/` from `trunk`)
Generating Pods project
Integrating client project
Pod installation complete! There are 11 dependencies from the Podfile and 13 total pods installed.
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS/HPHC $ cd ../../Android/
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/Android $ clear
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/Android $ open .
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/Android $ cd ..
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System $ cd iOS/
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS $ ls
HPHC                     README.md                sonar-project.properties
seifkobrosly@Sarie3:~/Development/nadph/FDA-My-Studies-Mobile-Application-System/iOS $ vi HPHC/
project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'


# Pods for FDA
def main_pods

  pod 'IQKeyboardManagerSwift'
  pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage'
  #pod 'RealmSwift'
  pod 'RealmSwift', '~> 3.20.0'
  pod 'CryptoSwift'
  pod 'ActionSheetPicker-3.0'

end

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  main_pods

end

target 'HPHCUITests' do
  use_frameworks!
  pod 'Embassy'
  pod 'EnvoyAmbassador'
end

target 'HPHCTests' do
  # inherit! :search_paths
"Podfile" 39L, 800C
project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'


# Pods for FDA
def main_pods

  pod 'IQKeyboardManagerSwift'
  pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage'
  pod 'RealmSwift', '~> 3.20.0' # <--- This will downgrade the current version.
  pod 'CryptoSwift'
  pod 'ActionSheetPicker-3.0'

end

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  main_pods

end

target 'HPHCUITests' do
  use_frameworks!
  pod 'Embassy'
  pod 'EnvoyAmbassador'
end

target 'HPHCTests' do
  # inherit! :search_paths

  pod 'Mockingjay', '3.0.0-alpha.1'
end
~
project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'


# Pods for FDA
def main_pods

  pod 'IQKeyboardManagerSwift'
  pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage'
  #pod 'RealmSwift'
  pod 'RealmSwift', '~> 3.20.0'
  pod 'CryptoSwift'
  pod 'ActionSheetPicker-3.0'

end

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  main_pods

end

target 'HPHCUITests' do
  use_frameworks!
  pod 'Embassy'
  pod 'EnvoyAmbassador'
end

target 'HPHCTests' do
  # inherit! :search_paths

  pod 'Mockingjay', '3.0.0-alpha.1'
end
~
~

**Comment by seifscape** [comment]
> @FDA-MyStudies - unfortunately, you are incorrect. It still does not build:
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/27783894/72536112-a2992380-3847-11ea-8a90-fe2086189037.png">
> 
> Neither does the Android - even after we fixed a different java error:
> 
> ![image](https://user-images.githubusercontent.com/27783894/72536201-d07e6800-3847-11ea-9bea-f43aefdd4d9a.png)
> 
> Does one of the previous branches work? Or any suggestions on how to get these to even build to work with it?

I am also stuck trying to get the Android version to work with the R.java file not being generated for some reason. If you have made any progress it would be greatly appreciated.

For iOS update the Podfile to this:

```
project 'HPHC.xcodeproj/'

# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'


# Pods for FDA
def main_pods

  pod 'IQKeyboardManagerSwift'
  pod 'SlideMenuControllerSwift', :git => 'https://github.com/AtomicSLLC/SlideMenuControllerSwift.git', :branch => 'swift5'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'SDWebImage'
  pod 'RealmSwift', '~> 3.20.0'
  pod 'CryptoSwift'
  pod 'ActionSheetPicker-3.0'

end

target 'HPHC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  main_pods

end

target 'HPHCUITests' do
  use_frameworks!
  pod 'Embassy'
  pod 'EnvoyAmbassador'
end

target 'HPHCTests' do
  # inherit! :search_paths

  pod 'Mockingjay', '3.0.0-alpha.1'
end
```

**Comment by FDA-MyStudies** [comment]
Hi @seifscape  and @doomlab ,

Below few approaches you can try to resolve this issue.
1) Select correct Target "HPHC"
2) Update Cocoapods.
3) Clean the build directory and re-build

It would be helpful if you provide the more details about the error, as we are unable to provide appropriate responses from screenshots alone.  Feel free to reach out to me directly at vasantk@boston-technology.com, and we can trouble shoot this issue together. 

Thanks,
Vasant
