### ISSUE TITLE
fdahpStudyDesigner maven build fails - "unmappable character for encoding utf-8"

### ISSUE THREAD

**Issue by u84six** [PopMedNet-Team/Mobile-Application#22]
The pom.xml files configure the maven plugins to use utf-8 encoding, but this will throw an error and fail the build unless you change the encoding to ISO-8859-1 when building on Ubuntu.

**Comment by rbudrevich** [comment]
because all those iso chars seem to be in the file header comments and unnecessary fluff like fancy quotes, i tried dropping them all and it does compile under utf8:

find . -name "*.java" | xargs -i% sed -i 's/\o223//g' %
find . -name "*.java" | xargs -i% sed -i 's/\o224//g' %
find . -name "*.java" | xargs -i% sed -i 's/\o226//g' %
find . -name "*.java" | xargs -i% sed -i 's/\o251//g' %
find . -name "*.java" | xargs -i% sed -i 's/\o302//g' %
find . -name "*.java" | xargs -i% sed -i 's/\o342\o200\o234//g' %
find . -name "*.java" | xargs -i% sed -i 's/\o342\o200\o235//g' %

**Comment by FDA-MyStudies** [comment]
Hi @u84six,

Thank you for your interest in the MyStudies system. Apologies for the eight-month delay in responding.  We only recently acquired additional funding to support open-source activities.  In regards to your original question:

This will be resolved by adding below link in pom.xml file

<properties>
           <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>

By adding this line in pom.xml will take care the encoding the source code. If your IDE (Eclipse or other) has default set to UTF-8, this issue won't occur.

Our latest release 2019.10 is addressed this issue, it works fine if you take the latest code from Gibhub.

Let us know if this helps you out.
