### ISSUE TITLE
fdahpStudyDesigner - HTTP 404 Not Found error

### ISSUE THREAD

**Issue by ghost** [PopMedNet-Team/Mobile-Application#50]
Hello,
I followed the steps in the FDA My Studies setup instructions and I was able to build the fdahpStudyDesigner and StudyMetaData projects without any issues, and after deploying the war files to my local Tomcat webapps folder, I get a HTTP Status 404 – Not Found error from Tomcat when trying to test if the fdahpStudyDesigner app is working in the browser (http://localhost:8080/fdahpStudyDesigner).

Of course, I checked the permissions, restarted Tomcat multiple times, but I still get this error, instead of being redirected to the WCP login page. This seems weird to me, as the StudyMetaData app is working fine (http://localhost:8080/StudyMetaData/ping is returning "It Works!"), so there seems to be no issue with the WCP web services.

My coworker went through the same setup on a different machine, and he is also getting the 404 Not Found error. We are both trying to run this on macOS 10.15.4 (Catalina), using Java 8, Tomcat 8.5, Maven 3.6, MySQL 5.7.

Do you have any idea why this issue could occur? Any help would be appreciated. Thanks!

**Comment by karpatit** [comment]
Hi,
I had the same problem and found that the problem was related to access permission for the file _application.properties_ and a the _file:///_ argument on one configuration file. 

In my case, I created a folder /home/fda and copied there the file _application.properties_ and give it permission to the tomcat user/group.

Then changed the path on the tomcat's _context.xml_ configuration file as follows:

`<Parameter name="property_file_location_prop" value="/home/fda/" override="1"/>`
`<Parameter name="property_file_name" value="application" override="1"/>`
`<Parameter name="property_file_location_config" value="file:///home/fda/application.properties" override="1"/>`
`<Parameter name="property_file_location_path" value="/home/fda/application.properties" override="1"/>`

This worked for me, hope it will work for you.

**Comment by ghost** [comment]
This actually worked, thanks! I never would have guessed I need to prefix the _property_file_location_config_ parameter with _file://_.
