### ISSUE TITLE
typo in the setup instructions, tomcat config

### ISSUE THREAD

**Issue by LucaCerina** [PopMedNet-Team/Mobile-Application#52]
Hello,
in the setup instructions file at page 8:
`<Parameter name="property_file_location_config" value="/usr/local/application.properties" override="1"/>`

should be:
`<Parameter name="property_file_location_config" value="file://usr/local/application.properties" override="1"/>.`

Generally it would be better to have a documentation that recalls the README files across the repo, I had to redo multiple parts, including the long recompilation of labkey development server, because the workflow of the pdf is not correct

**Comment by FDA-MyStudies** [comment]
Thank you for this feedback, @LucaCerina. And my sincere apologies about the long lag between your comment and my follow up. We are in the process of relaunching the latest code for this app into a new repo and plan be much more engaged going forward.

I'm going to keep this ticket open as a reminder to address this in our relaunched repo documentation, which will now be hosted online rather than in static PDFs so we can revise ongoing and not allow information to stagnate.

Thank you!
Amanda from the MyStudies team

**Comment by FDA-MyStudies** [comment]
I'm updating to confirm that the documentation was updated with this information. We're currently working to relaunch our code in a new repo that can be found here: https://github.com/FDA-MyStudies/FDA-My-Studies-Mobile-Application-System.

Some documentation and process items are still being revised, but I wanted to provide a link in case this is helpful.

Thank you!
Amanda from the MyStudies team
